version: 2
jobs:
  build:
    docker:
      - image: beevelop/android:latest

    working_directory: /opt/workspace/

    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout

      - restore_cache:
          key: homeassistant-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Setup environment
          command: .circleci/setup.sh

      - run:
          name: Compile apks
          command: ./gradlew --no-daemon assembleRelease

      - run:
          name: Copy artifacts
          command: |
            mkdir app/build/outputs/apks || true
            cp app/build/outputs/apk/phoneStandard/release/hass-*.apk app/build/outputs/apks/hass-gms.apk
            cp app/build/outputs/apk/phoneFdroid/release/hass-*.apk app/build/outputs/apks/hass-fdroid.apk
            mv app/build/outputs/apk/phoneStandard/release/hass-*.apk app/build/outputs/apk/phoneFdroid/release/hass-*.apk app/build/outputs/apks/

      - store_artifacts:
          path: app/build/outputs/apks/
          destination: apks/

      - store_artifacts:
          path: app/build/outputs/mapping/phoneStandard/release/mapping.txt
          destination: mappings/mapping-standard.txt

      - store_artifacts:
          path: app/build/outputs/mapping/phoneFdroid/release/mapping.txt
          destination: mappings/mapping-fdroid.txt

      - save_cache:
          key: homeassistant-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle/wrapper/dists/gradle-4.*-all/"
            - "~/.gradle/caches/modules-2/"
            - "~/.gradle/caches/4.*/"
            - "~/.gradle/caches/build-cache-1/"
            - "./.gradle/buildOutputCleanup"
            - "./.gradle/4.*/"
            - "~/.m2"