version: '2'
services:
    petiteannoncekmer-app:
        image: petiteannoncekmer
        external_links:
            - petiteannoncekmer-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petiteannoncekmer?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    petiteannoncekmer-mysql:
        extends:
            file: mysql.yml
            service: petiteannoncekmer-mysql
